import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

type Task={id:string;title:string;type:string;status:string;cost:string;time_minutes:number;approval_required:boolean;agent_can_execute:boolean};
type Opp={id:string;project:string;category:string;chain:string;reward:string;source:string;official_url:string;estimated_cost:number;estimated_time:number;risk_score:number;source_confidence:number;opportunity_score:number;analysis:string;tags:string[];tasks:Task[]};
const API=import.meta.env.VITE_API_BASE_URL||'http://127.0.0.1:8000';
const call=async<T>(p:string,o?:RequestInit):Promise<T>=>{const r=await fetch(API+p,o);if(!r.ok)throw Error(await r.text());return r.json()};
function App(){const [online,setOnline]=useState(false),[items,setItems]=useState<Opp[]>([]),[sel,setSel]=useState<Opp|null>(null),[tab,setTab]=useState('hunter'),[q,setQ]=useState(''),[cat,setCat]=useState('ALL'),[min,setMin]=useState(0),[msg,setMsg]=useState('Готово');
 const [stats,setStats]=useState<any>({}),[agents,setAgents]=useState<any[]>([]),[chains,setChains]=useState<any[]>([]);
 const load=async()=>{try{const [a,b,c,d]=await Promise.all([call<{items:Opp[]}>(`/api/hunter/opportunities?min_score=${min}`),call<any>('/api/hunter/stats'),call<any>('/api/hunter/agents'),call<any>('/api/hunter/contract-lab/chains')]);setItems(a.items||[]);setStats(b);setAgents(c.agents||[]);setChains(d.chains||[]);setOnline(true)}catch{setOnline(false);setMsg('Backend недоступний')}};
 useEffect(()=>{load()},[min]);
 const visible=items.filter(x=>(cat==='ALL'||x.category===cat)&&(!q||`${x.project} ${x.chain} ${x.reward} ${x.source}`.toLowerCase().includes(q.toLowerCase())));
 const scan=async()=>{setMsg('Сканування CryptoRank + INCRYPTED…');try{const r=await call<any>('/api/hunter/scan',{method:'POST'});setItems(r.items||[]);setMsg(`Скан завершено. Нових/оновлених: ${r.new}`);await load()}catch(e){setMsg('Помилка сканування')}};
 const analyze=async()=>{if(!sel)return;try{setSel(await call<Opp>(`/api/hunter/opportunities/${sel.id}/analyze`,{method:'POST'}));setMsg('AI-аналіз готовий')}catch{setMsg('Помилка AI-аналізу')}};
 const prepare=async(t:Task)=>{if(!sel)return;try{const r=await call<any>(`/api/hunter/opportunities/${sel.id}/tasks/${t.id}/prepare`,{method:'POST'});setSel(await call<Opp>(`/api/hunter/opportunities/${sel.id}`));setMsg(r.message)}catch{setMsg('Помилка підготовки task')}};
 const approve=async(t:Task,v:boolean)=>{if(!sel)return;try{await call<any>(`/api/hunter/opportunities/${sel.id}/tasks/${t.id}/approve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approved:v})});setSel(await call<Opp>(`/api/hunter/opportunities/${sel.id}`));setMsg(v?'Approval надано':'Дію відхилено')}catch{setMsg('Помилка approval')}};
 return <div className="app"><header><div><b>ARC AI HUB</b><small>DROP HUNTER v0.9</small></div><span className={online?'on':'off'}>● {online?'ONLINE':'OFFLINE'}</span></header>
 <nav>{[['hunter','🔎 Opportunities'],['tasks','✅ My Tasks'],['agents','🤖 Agents'],['contracts','🧩 Contract Lab']].map(([k,t])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{t}</button>)}</nav>
 <main>{tab==='hunter'&&<><section className="hero"><div><span>WEB3 REWARDS OPERATING SYSTEM</span><h1>Знаходимо → оцінюємо → готуємо → виконуємо</h1><p>AI-агенти шукають можливості, рахують пріоритет, будують checklist і зупиняються перед авторизованими діями.</p></div><button className="primary" onClick={scan}>🚀 Scan</button></section>
 <section className="stats">{[['total','можливостей'],['high_score','score ≥ 70'],['testnets','testnets'],['airdrops','airdrops'],['approval_tasks','approval']].map(x=><div key={x[0]}><b>{stats[x[0]]||0}</b><small>{x[1]}</small></div>)}</section>
 <section className="toolbar"><input placeholder="Пошук…" value={q} onChange={e=>setQ(e.target.value)}/><select value={cat} onChange={e=>setCat(e.target.value)}><option>ALL</option><option>TESTNET</option><option>AIR_DROP</option></select><label>Min <input type="number" min="0" max="100" value={min} onChange={e=>setMin(+e.target.value)}/></label></section>
 <div className="grid"><section className="panel"><h2>Opportunity Board <small>{visible.length}</small></h2>{visible.map(x=><article className={sel?.id===x.id?'selected':''} onClick={()=>call<Opp>(`/api/hunter/opportunities/${x.id}`).then(setSel)} key={x.id}><div><h3>{x.project}<em>{x.opportunity_score}</em></h3><small>{x.category} · {x.chain} · {x.source}</small><p>{x.reward}</p></div><small>{x.estimated_time}m · ${x.estimated_cost}</small></article>)}</section>
 <aside className="panel">{!sel?<div className="empty"><b>Оберіть opportunity</b></div>:<><h2>{sel.project}<em>{sel.opportunity_score}</em></h2><div className="metrics"><span>Risk <b>{sel.risk_score}</b></span><span>Source <b>{sel.source_confidence}%</b></span><span>Time <b>{sel.estimated_time}m</b></span><span>Cost <b>${sel.estimated_cost}</b></span></div><p className="analysis">{sel.analysis}</p><div className="buttons"><a href={sel.official_url} target="_blank" rel="noreferrer">Official ↗</a><button onClick={analyze}>🧠 AI Analyze</button></div><h3>Action Checklist</h3>{sel.tasks.map(t=><div className="task" key={t.id}><div><b>{t.title}</b><small>{t.type} · {t.time_minutes}m</small></div><div>{t.agent_can_execute&&!t.approval_required&&<span className="auto">AI AUTO</span>}{t.approval_required&&<span className="approval">APPROVAL</span>}<button onClick={()=>prepare(t)}>Prepare</button>{t.approval_required&&t.status==='READY_FOR_APPROVAL'&&<><button onClick={()=>approve(t,true)}>Approve</button><button onClick={()=>approve(t,false)}>Reject</button></>}</div></div>)}</>}</aside></div><p className="msg">{msg}</p></>}
 {tab==='tasks'&&<section className="page"><h1>My Tasks</h1><p>Єдиний checklist: AI AUTO, APPROVAL, proof та майбутній reward tracking. Браузерні та blockchain adapters підключимо після стабілізації ядра.</p></section>}
 {tab==='agents'&&<section className="page"><h1>Agents</h1><div className="cards">{agents.map(a=><article key={a.id}><b>{a.name}</b><p>{a.role}</p><span>{a.mode}</span></article>)}</div></section>}
 {tab==='contracts'&&<section className="page"><h1>Contract Lab</h1><p>Підготовка deployment-планів для потрібних мереж. Підписання транзакцій завжди окремий approval gate.</p><div className="cards">{chains.map(c=><article key={c.key}><b>{c.name}</b><small>Chain ID {c.chain_id}</small><span>{c.deployment}</span></article>)}</div></section>}</main><footer>No seed phrase · No private key · No invisible signing · User approval required</footer></div>}
createRoot(document.getElementById('root')!).render(<App/>);
